<?php

function custom_module_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
  switch($op){
    case 'presave':
      if($node->type == 'zone'){
        $node->field_zone_wkt[0]['openlayers_wkt'] = "GEOMETRYCOLLECTION(POLYGON(" 
                                                      . $node->field_zone_min_lon[0]['value']
                                                      . " " 
                                                      . $node->field_zone_max_lat[0]['value'] 
                                                      . ", "
                                                      . $node->field_zone_max_lon[0]['value']
                                                      . " "
                                                      . $node->field_zone_max_lat[0]['value']
                                                      . ", "
                                                      . $node->field_zone_max_lon[0]['value']
                                                      . " "
                                                      . $node->field_zone_min_lat[0]['value']
                                                      . ", "
                                                      . $node->field_zone_min_lon[0]['value']
                                                      . " "
                                                      . $node->field_zone_min_lat[0]['value']
                                                      . "))";
      }
      if($node->type == 'survey'){
        $parent_nid_zone = $node->nodehierarchy_menu_links[0]['pnid'];
        /*
        $parent_zone = node_load($parent_nid_zone);
        $parent_zone_title = $parent_zone->title;
        $node->field_survey_parent_zone[0]['value'] = $parent_zone_title;
        */
        $node->field_survey_parent_zone_ref[0]['nid'] = $parent_nid_zone;
        
      }
      if($node->type == 'line'){
        $parent_nid_survey = $node->nodehierarchy_menu_links[0]['pnid'];
        $node->field_line_parent_survey_ref[0]['nid'] = $parent_nid_survey;
        
        $result = db_query("SELECT field_survey_parent_zone_ref_nid FROM {content_type_survey} WHERE nid = '%d'", $parent_nid_survey);
        $row = db_fetch_array($result);
        $parent_nid_zone = $row['field_survey_parent_zone_ref_nid'];        
        $node->field_line_parent_zone_ref[0]['nid'] = $parent_nid_zone;
        
        /*
        $parent_survey = node_load($parent_nid_survey);
        $parent_survey_title = $parent_survey->title;
        $node->field_line_parent_survey[0]['value'] = $parent_survey_title;
        */
        /*
        $parent_zone_title = $parent_survey->field_survey_parent_zone[0]["value"];
        $node->field_line_parent_zone[0]['value'] = $parent_zone_title;
        */
        
        if (isset($node->field_line_ocean_prof_image[0]["filename"])){
          $node->field_line_has_ocean_prof[0][value] = "*";
          $node->nodehierarchy_menu_links[0]["customized"] = 1;
          $node->nodehierarchy_menu_links[0]["link_title"] = $node->title . " *";
        } else {
          $node->field_line_has_ocean_prof[0][value] = "";
        }
        
        $node->field_line_wkt[0]['openlayers_wkt'] = "GEOMETRYCOLLECTION(LINESTRING("
                                                      . $node->field_sol_lon_field[0]['value']
                                                      . " "
                                                      . $node->field_sol_lat_field[0]['value']
                                                      . ", "
                                                      . $node->field_eol_lon_field[0]['value']
                                                      . " "
                                                      . $node->field_eol_lat_field[0]['value']
                                                      . "))";
        $node->field_line_points_wkt[0]['openlayers_wkt'] = "GEOMETRYCOLLECTION(POINT("
                                                      . $node->field_sol_lon_field[0]['value']
                                                      . " "
                                                      . $node->field_sol_lat_field[0]['value']
                                                      . "),POINT("
                                                      . $node->field_eol_lon_field[0]['value']
                                                      . " "
                                                      . $node->field_eol_lat_field[0]['value']
                                                      . "))";
      }
    break;
    
    case 'update':
      if($node->type == 'survey'){
        $result =db_query("SELECT mlid, plid, has_children, weight FROM {menu_links} WHERE menu_name = 'primary-links' and link_path = '%s'", 'node/' .  $node->nid);
        $row = db_fetch_array($result);
        $mlid = $row['mlid'];
        $plid = $row['plid'];
        $has_children = $row['has_children'];
        $weight = $row['weight'];
        
        $item = array(
          'mlid' => $mlid,
          'menu_name' => 'primary-links',
          'link_path' => 'node/' . $node->nid,
          'link_title' => $node->title,
          'plid' => $plid,
          'weight' => $weight,
          'module' => 'nodehierarchy',
          'has_children' => $has_children,
          'hidden' => 0
        );
        menu_link_save($item);
        
        $result = db_query("UPDATE 
                              {content_type_survey} 
                            SET 
                              field_survey_parent_zone_ref_nid = 
                                (SELECT nid FROM 
                                  {nodehierarchy_menu_links} 
                                 WHERE mlid =
                                  (SELECT plid FROM 
                                    {menu_links} 
                                   WHERE 
                                     menu_name = 'primary-links' AND link_path = '%s'))
                            WHERE
                              nid = %d", 'node/' . $node->nid, $node->nid);
      }
      
      if($node->type == 'line'){
        $result =db_query("SELECT mlid, plid, weight FROM {menu_links} WHERE menu_name = 'primary-links' and link_path = '%s'", 'node/' .  $node->nid);
        $row = db_fetch_array($result);
        $mlid = $row['mlid'];
        $plid = $row['plid'];
        $weight = $row['weight'];
        
        $result = db_query("SELECT nid FROM 
                              {nodehierarchy_menu_links} 
                            WHERE mlid =
                              (SELECT plid FROM 
                                {menu_links} 
                               WHERE 
                                 menu_name = 'primary-links' AND link_path = '%s')", 'node/' . $node->nid);
        $row = db_fetch_array($result);
        $parent_nid = $row['nid'];
                                     
        $result = db_query("UPDATE 
                              {content_type_line} 
                            SET 
                              field_line_parent_survey_ref_nid = %d 
                            WHERE nid = %d", $parent_nid, $node->nid);
                                     
        db_query("UPDATE 
                    {content_type_line} 
                  SET 
                    field_line_parent_zone_ref_nid = 
                      (SELECT nid FROM
                        {nodehierarchy_menu_links} 
                       WHERE mlid = 
                        (SELECT plid FROM
                          {menu_links} 
                         WHERE
                           menu_name = 'primary-links' AND link_path = '%s'))
                  WHERE nid = %d", 'node/' . $parent_nid, $node->nid);
        
        $item = array(
          'mlid' => $mlid,
          'menu_name' => 'primary-links',
          'link_path' => 'node/' . $node->nid,
          'link_title' => $node->title . " " . $node->field_line_has_ocean_prof[0][value],
          'plid' => $plid,
          'weight' => $weight,
          'module' => 'nodehierarchy',
          'hidden' => 0
        );
        menu_link_save($item);
      }
    break;
  }
}
