<?php

function custom_module_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
  switch($op){
    case 'presave':
      if($node->type == 'subzone'){
        $parent_nid_zone = $node->nodehierarchy_menu_links[0]['pnid'];
        $parent_zone = node_load($parent_nid_zone);
        $parent_zone_title = $parent_zone->title;
        $node->field_subzone_parent_zone_field[0]['value'] = $parent_zone_title;
      }
      if($node->type == 'survey'){
        $parent_nid_subzone = $node->nodehierarchy_menu_links[0]['pnid'];
        $parent_subzone = node_load($parent_nid_subzone);
        $parent_subzone_title = $parent_subzone->title;
        $node->field_survey_parent_subzone[0]['value'] = $parent_subzone_title;
        
        $parent_nid_zone = $parent_subzone->nodehierarchy_menu_links[0]['pnid'];
        $parent_zone = node_load($parent_nid_zone);
        $parent_zone_title = $parent_zone->title;
        $node->field_survey_parent_zone[0]['value'] = $parent_zone_title;
      }
      if($node->type == 'line'){
        $parent_nid_survey = $node->nodehierarchy_menu_links[0]['pnid'];
        $parent_survey = node_load($parent_nid_survey);
        $parent_survey_title = $parent_survey->title;
        $node->field_line_parent_survey[0]['value'] = $parent_survey_title;
        
        $parent_nid_subzone = $parent_survey->nodehierarchy_menu_links[0]['pnid'];
        $parent_subzone = node_load($parent_nid_subzone);
        $parent_subzone_title = $parent_subzone->title;
        $node->field_line_parent_subzone[0]['value'] = $parent_subzone_title;
        
        $parent_nid_zone = $parent_subzone->nodehierarchy_menu_links[0]['pnid'];
        $parent_zone = node_load($parent_nid_zone);
        $parent_zone_title = $parent_zone->title;
        $node->field_line_parent_zone[0]['value'] = $parent_zone_title;
      } 
    break;
  }
}
